# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deno-api
  labels:
    components: deno-api
    # tier: frontend
spec:
  selector:
    matchLabels:
      component: deno-api
      # tier: frontend
  template:
    metadata:
      labels:
        component: deno-api
        # tier: frontend
    spec:
      containers:
        - name: deno-docker
          image: deno-docker:0.0.4
          imagePullPolicy: Never
          resources: {}
          ports:
            - containerPort: 1993
