# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-api
  labels:
    components: rust-api
    # tier: frontend
spec:
  selector:
    matchLabels:
      component: rust-api
      # tier: frontend
  template:
    metadata:
      labels:
        component: rust-api
        # tier: frontend
    spec:
      containers:
        - name: rust-docker
          image: rust-docker
          imagePullPolicy: Never
          resources: {}
          ports:
            - containerPort: 3009
