# Create a deployment with
# `kubectl create -f manifest.yaml`
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-api
  creationTimestamp: null
  labels:
    app: rust-api

spec:
  # type: NodePort
  # ports:
  #   # access service via this external port number
  #   - nodePort: 30163
  #     # port number exposed internally in cluster
  #     port: 3009
  #     # port that the containers are listening on
  #     targetPort: 3009
  replicas: 3
  selector:
    matchLabels:
      app: rust-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rust-api
    spec:
      # the name passed to docker
      # `docker build -t deno-docker
      containers:
        - image: rust-docker
          name: rust-docker
          # tell the Kubernetes docker daemon to not pull
          imagePullPolicy: Never
          resources: {}
          ports:
            - containerPort: 1993
status: {}
